import type { Customer } from "@/models/customer";

export type TrainerReportPlan = {
  plan: Customer;
  /** Commission generated by this plan in the current business month. */
  commissionAmount: number;
};

export type TrainerReport = {
  name: string;
  plans: TrainerReportPlan[];
  totalCommission: number;
};
